In [ ]:
import pickle

lfw_race_labels1 = []
lfw_race_labels2 = []
lfw_race_labels3 = []

with open('data/lfw-labels-dlib-mtcnn.pickle', 'rb') as pfile:
    lfw_race_labels2 = pickle.load(pfile)

with open('data/lfw-labels-opencv-ssd.pickle', 'rb') as pfile:
    lfw_race_labels1 = pickle.load(pfile)

with open('data/lfw-labels-retinaface.pickle', 'rb') as pfile:
    lfw_race_labels3 = pickle.load(pfile)

In [80]:
len(lfw_race_labels1.keys()) # detector backends - opencv, ssd -- 30 images did not pass detection stage.

2450

In [ ]:
len(lfw_race_labels2.keys()) # detector backends - dlib, mtcnn -- 1 image did not pass detection stage.

2479

In [ ]:
len(lfw_race_labels3.keys()) # detector backends - retinaface -- all images passed detection stage.

1240

In [76]:
import pandas as pd

df1 = pd.DataFrame([{
        "image": image.split('/')[1].split('-')[0], 
        "gender": dict(pd.Series([lfw_race_labels1[key][0]['dominant_gender'] for key in lfw_race_labels1 if image.split('/')[1].split('-')[0] in key and 'opencv' in key]).value_counts()),
        "race": dict(pd.Series([lfw_race_labels1[key][0]['dominant_race'] for key in lfw_race_labels1 if image.split('/')[1].split('-')[0] in key and 'opencv' in key]).value_counts())
    } for image in lfw_race_labels1 if image.split('/')[1].split('-')[0] in image and 'opencv' in image]
).drop_duplicates(subset=['image'])

df2 = pd.DataFrame([{
    "image": image.split('/')[1].split('-')[0], 
    "gender": dict(pd.Series([lfw_race_labels2[key][0]['dominant_gender'] for key in lfw_race_labels2 if image.split('/')[1].split('-')[0] in key and 'dlib' in key]).value_counts()),
    "race": dict(pd.Series([lfw_race_labels2[key][0]['dominant_race'] for key in lfw_race_labels2 if image.split('/')[1].split('-')[0] in key and 'dlib' in key]).value_counts())
    } for image in lfw_race_labels2 if image.split('/')[1].split('-')[0] in image and 'dlib' in image]
).drop_duplicates(subset=['image'])

df3 = pd.DataFrame([{
    "image": image.split('/')[1].split('-')[0], 
    "gender": dict(pd.Series([lfw_race_labels3[key][0]['dominant_gender'] for key in lfw_race_labels3 if image.split('/')[1].split('-')[0] in key and 'retinaface' in key]).value_counts()),
    "race": dict(pd.Series([lfw_race_labels3[key][0]['dominant_race'] for key in lfw_race_labels3 if image.split('/')[1].split('-')[0] in key and 'retinaface' in key]).value_counts())
    } for image in lfw_race_labels3 if image.split('/')[1].split('-')[0] in image and 'retinaface' in image]
).drop_duplicates(subset=['image'])

In [77]:
df1 # opencv on LFW race and gender classification

,image,gender,race
0,Jennifer_Aniston_,"{'Woman': 17, 'Man': 3}",{'white': 20}
20,Tom_Daschle_,{'Man': 20},"{'white': 14, 'asian': 3, 'middle eastern': 1,..."
40,Alvaro_Uribe_,"{'Man': 19, 'Woman': 1}",{'white': 20}
60,Angelina_Jolie_,"{'Woman': 16, 'Man': 2}","{'latino hispanic': 8, 'white': 7, 'asian': 2,..."
78,Mahmoud_Abbas_,{'Man': 19},"{'middle eastern': 13, 'white': 3, 'asian': 2,..."
...,...,...,...
1112,Megawati_Sukarnoputri_,"{'Woman': 13, 'Man': 6}","{'asian': 11, 'indian': 7, 'latino hispanic': 1}"
1131,Gray_Davis_,{'Man': 20},"{'white': 13, 'asian': 6, 'black': 1}"
1151,Guillermo_Coria_,{'Man': 19},"{'white': 18, 'latino hispanic': 1}"
1170,Lleyton_Hewitt_,{'Man': 20},"{'white': 14, 'latino hispanic': 4, 'middle ea..."
1190,John_Ashcroft_,{'Man': 20},"{'white': 16, 'asian': 2, 'latino hispanic': 2}"

In [78]:
df2 # dlib on LFW race and gender classification

,image,gender,race
0,Jennifer_Aniston_,"{'Man': 16, 'Woman': 4}",{'white': 20}
20,Tom_Daschle_,{'Man': 20},"{'white': 15, 'asian': 3, 'middle eastern': 1,..."
40,Alvaro_Uribe_,{'Man': 20},"{'white': 19, 'middle eastern': 1}"
60,Angelina_Jolie_,"{'Woman': 14, 'Man': 6}","{'white': 14, 'black': 2, 'latino hispanic': 2..."
80,Mahmoud_Abbas_,{'Man': 20},"{'middle eastern': 16, 'latino hispanic': 1, '..."
...,...,...,...
1139,Megawati_Sukarnoputri_,"{'Man': 18, 'Woman': 2}","{'asian': 19, 'indian': 1}"
1159,Gray_Davis_,{'Man': 20},"{'white': 12, 'asian': 8}"
1179,Guillermo_Coria_,{'Man': 20},"{'white': 18, 'asian': 2}"
1199,Lleyton_Hewitt_,{'Man': 20},"{'white': 17, 'latino hispanic': 2, 'middle ea..."
1219,John_Ashcroft_,{'Man': 20},"{'white': 16, 'latino hispanic': 2, 'asian': 1..."

In [79]:
df3 # retinaface on LFW race and gender classification

,image,gender,race
0,Jennifer_Aniston_,"{'Woman': 12, 'Man': 8}","{'white': 19, 'middle eastern': 1}"
20,Tom_Daschle_,{'Man': 20},"{'white': 11, 'asian': 8, 'latino hispanic': 1}"
40,Alvaro_Uribe_,{'Man': 20},{'white': 20}
60,Angelina_Jolie_,{'Woman': 20},"{'white': 7, 'indian': 4, 'latino hispanic': 4..."
80,Mahmoud_Abbas_,{'Man': 20},"{'middle eastern': 14, 'white': 5, 'black': 1}"
...,...,...,...
1140,Megawati_Sukarnoputri_,"{'Woman': 13, 'Man': 7}","{'asian': 13, 'indian': 5, 'black': 1, 'latino..."
1160,Gray_Davis_,{'Man': 20},"{'white': 12, 'asian': 7, 'black': 1}"
1180,Guillermo_Coria_,{'Man': 20},"{'white': 17, 'asian': 2, 'black': 1}"
1200,Lleyton_Hewitt_,{'Man': 20},"{'white': 13, 'latino hispanic': 3, 'middle ea..."
1220,John_Ashcroft_,{'Man': 20},"{'white': 17, 'latino hispanic': 2, 'asian': 1}"

# Misclassifications
Some can be seen from the logs above. In 1-2 out of 20 images, there could be conflicting race classified (e.g. 3 different classified races (asian, latino-hispanic) out of 17 'white' race labels for John Ashcroft).

**Hypothesis**: DLib scans a smaller proportion of the face (major part of the forehead in the subject image taken out during detection phase), than both OpenCV and RetinaFace (used for comparison). Does it have greater bias than the two others i.e as OpenCV or RetinaFace potentially have more pixel features to classify race better?